<?php
 $buku = [
    "no_urut" => "01",
    "judul" => "Roh",
    "genre" => "Horor",
    "penulis" => "Asma nadia",
    "penerbit" => "Mirzani",
    "tahun_terbit" => "2015",
 ],
 [
    "no_urut" => "02",
    "judul" => "Kuntilanak",
    "genre" => "Horor",
    "penulis" => "Tere liye",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2013",
 ],
 [
    "no_urut" => "03",
    "judul" => "Dilan 1990",
    "genre" => "Romance",
    "penulis" => "Pidi baiq",
    "penerbit" => "Pastel books",
    "tahun_terbit" => "2014",
 ],
 [
    "no_urut" => "04",
    "judul" => "Rindu",
    "genre" => "Romance",
    "penulis" => "Tere liye",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2012",
 ],
 [
    "no_urut" => "05",
    "judul" => "Nyi roro kidul",
    "genre" => "Sejarah",
    "penulis" => "W.S. Rendra",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "1998",
 ],
 [
    "no_urut" => "06",
    "judul" => "Cerita-cerita Seram",
    "genre" => "Horor",
    "penulis" => "Risa saraswati",
    "penerbit" => "Gagas media",
    "tahun_terbit" => "2013",
 ],
 [
    "no_urut" => "07",
    "judul" => "Perahu Kertas",
    "genre" => "Romance",
    "penulis" => "Dee Lestari",
    "penerbit" => "Bentang pustaka",
    "tahun_terbit" => "2012",
 ],
 [
    "no_urut" => "08",
    "judul" => "Sehidup Semati",
    "genre" => "Romance",
    "penulis" => "Emina",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2015",
 ],
 [
    "no_urut" => "09",
    "judul" => "Cinta dan rahasia",
    "genre" => "Romance",
    "penulis" => "Asma nadia",
    "penerbit" => "Mizania",
    "tahun_terbit" => "2014",
 ],
 [
    "no_urut" => "10",
    "judul" => "Buku Cinta",
    "genre" => "Romance",
    "penulis" => "Tere Liye",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2013",
 ],
 [
    "no_urut" => "11",
    "judul" => "Cinta dalam sepotong roti",
    "genre" => "Romance",
    "penulis" => "Maman suherman",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2017",
 ],
 [
    "no_urut" => "12",
    "judul" => "Sisi lain",
    "genre" => "Horor",
    "penulis" => "Risa saraswati",
    "penerbit" => "GagasMedia",
    "tahun_terbit" => "2013",
 ],
 [
    "no_urut" => "13",
    "judul" => "Kisah seram di sekolah",
    "genre" => "Horor",
    "penulis" => "Tere Liye",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2013",
 ],
 [
    "no_urut" => "14",
    "judul" => "Cinta dan hujan di bulan desember",
    "genre" => "Romance",
    "penulis" => "Leila S. Chudori",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2014",
 ],
 [
    "no_urut" => "15",
    "judul" => "Siti nurbaya",
    "genre" => "Romance",
    "penulis" => "Marah Roesli",
    "penerbit" => "Balai pustaka",
    "tahun_terbit" => "1922",
 ],
 [
    "no_urut" => "16",
    "judul" => "Sang Pemimpi",
    "genre" => "Drama",
    "penulis" => "Andrea Hirata",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2006",
 ],
 [
    "no_urut" => "17",
    "judul" => "Ayat ayat cinta",
    "genre" => "Romance",
    "penulis" => "Habiburahman El Shirazy",
    "penerbit" => "Republika",
    "tahun_terbit" => "2004",
 ],
 [
    "no_urut" => "18",
    "judul" => "Pengabdi Setan",
    "genre" => "Horor",
    "penulis" => "Joko Anwar",
    "penerbit" => "Mizan",
    "tahun_terbit" => "2012",
 ],
 [
    "no_urut" => "19",
    "judul" => "Gadis di dalam koper",
    "genre" => "Horor",
    "penulis" => "Dewa Nyoman A.Suryawan",
    "penerbit" => "GagasMedia",
    "tahun_terbit" => "2013",
 ],
 [
    "no_urut" => "20",
    "judul" => "Laut bercerita",
    "genre" => "Horor",
    "penulis" => "Leila S.Chudori",
    "penerbit" => "Gramedia",
    "tahun_terbit" => "2017",
 ],

 foreach ($buku as $data){
   
 }
?>